---
- functions:
  - {name: undefined, within: []}
  - {name: traceShowId, within: []}
  - {name: print, within: []}
  - {name: traceShow, within: []}
  - {name: nullPtr, within: []}

- error: {lhs: "if p then x else pure ()", rhs: "when p x"}

- fixity: infixr 8 .*
- fixity: infixr 8 .**
