---
- functions:
  - {name: undefined, within: []}
  - {name: traceShowId, within: []}
  - {name: print, within: []}
  - {name: traceShow, within: []}

- error: {lhs: "if p then x else pure ()", rhs: "when p x"}
- ignore: {name: Use lambda-case}

- fixity: infixr 8 .*
- fixity: infixr 8 .**
