---
sudo: false
language: c
addons:
  apt:
    packages:
    - libgmp3-dev
    - libarchive-dev
matrix:
  include:

  - env: TARGET=x86_64-unknown-linux GHC=8.4.4
    addons:
      apt:
        update: true
        sources:
        - hvr-ghc
        packages:
        - ghc-8.8.1
        - cabal-install-3.0
        - libarchive-dev

  - env: TARGET=x86_64-unknown-linux GHC=8.6.5
    addons:
      apt:
        update: true
        sources:
        - hvr-ghc
        packages:
        - ghc-8.6.5
        - cabal-install-3.0
        - libarchive-dev

  - env: TARGET=x86_64-unknown-linux GHC=8.4.4
    addons:
      apt:
        update: true
        sources:
        - hvr-ghc
        packages:
        - ghc-8.4.4
        - cabal-install-3.0
        - libarchive-dev

  # OS X
  - env: TARGET=x86_64-apple-darwin GHC=8.8.1
    os: osx

before_install:
- |
  if [ `uname` = "Darwin" ]
  then
    brew install libarchive
    brew install ghc
    brew install cabal-install
    export PKG_CONFIG_PATH="/usr/local/opt/libarchive/lib/pkgconfig"
    cabal update
  else
    export PATH=/opt/ghc/bin:$PATH
    cabal update
  fi

script:
- curl -sL https://raw.github.com/ndmitchell/hlint/master/misc/travis.sh | sh -s src test bench
- cabal update
- travis_wait 40 cabal test
